# Generated by Django 6.0 on 2025-12-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('actualites', 'Actualités'), ('sermon', 'Sermon'), ('article', 'Article'), ('annonce', 'Annonce'), ('temoignage', 'Témoignage'), ('evenement', 'Événement'), ('enseignement', 'Enseignement'), ('priere', 'Prière'), ('louange', 'Louange'), ('jeunesse', 'Jeunesse'), ('femmes', 'Femmes'), ('hommes', 'Hommes'), ('enfants', 'Enfants'), ('missions', 'Missions'), ('projets', 'Projets')], default='article', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/', verbose_name='Image mise en avant'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié'), ('archivé', 'Archivé')], default='brouillon', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Vues'),
        ),
    ]
