# Generated by Django 6.0 on 2025-12-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('event_type', models.CharField(choices=[('SERVICE', 'Culte'), ('PRAYER', 'Réunion de prière'), ('BIBLE_STUDY', 'Étude biblique'), ('YOUTH', 'Jeunesse'), ('SPECIAL', 'Événement spécial')], max_length=50, verbose_name='Type')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('speaker', models.CharField(blank=True, max_length=100, verbose_name='Orateur')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
    ]
