# Generated by Django 6.0 on 2025-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('SERVICE', 'Culte'), ('PRAYER', 'Groupe de prière'), ('BIBLE_STUDY', 'Étude biblique'), ('YOUTH', 'Jeunesse'), ('SPECIAL', 'Événement spécial'), ('MEETING', 'Réunion'), ('WORKSHOP', 'Atelier')], default='SERVICE', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, verbose_name='Intervenant'),
        ),
    ]
