# Generated by Django 6.0 on 2025-12-22 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_updated_at_alter_event_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='Extrait'),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
    ]
