# Generated by Django 6.0 on 2025-12-22 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_description_remove_event_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('service', 'Culte'), ('prayer', 'Prière'), ('conference', 'Conférence'), ('youth', 'Jeunesse'), ('worship', 'Louange'), ('other', 'Autre')], default='other', max_length=50, verbose_name="Type d'événement"),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(blank=True, max_length=200, verbose_name='Intervenant/Prédicateur'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'is_published'], name='events_even_event_t_4cd3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'is_published'], name='events_even_date_cba99e_idx'),
        ),
    ]
