# Generated by Django 6.0 on 2025-12-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_duration_event_event_type_event_speaker_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_event_t_4cd3d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_date_cba99e_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
    ]
