# Generated by Django 6.0 on 2025-12-22 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='summernote_attachments/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document')], default='image', max_length=50, verbose_name='Type de fichier')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier média',
                'verbose_name_plural': 'Fichiers médias',
                'ordering': ['-upload_date'],
            },
        ),
    ]
