# Generated by Django 6.0 on 2025-12-10 21:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('PASTOR', 'Pasteur'), ('ELDER', 'Ancien'), ('DEACON', 'Diacre'), ('MEMBER', 'Membre'), ('VISITOR', 'Visiteur')], default='MEMBER', max_length=20, verbose_name='Rôle')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('membership_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adhésion")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
