# Generated by Django 6.0 on 2025-12-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visiteur'), ('MEMBER', 'Membre'), ('DEACON', 'Diacre'), ('ELDER', 'Ancien'), ('PASTOR', 'Pasteur'), ('ADMIN', 'Administrateur'), ('WEBMASTER', 'Webmaster')], default='MEMBER', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
