# Generated by Django 6.0 on 2025-12-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_role_alter_member_user_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('VISITOR', 'Visiteur'), ('MEMBER', 'Membre'), ('DEACON', 'Diacre'), ('ELDER', 'Ancien'), ('PASTOR', 'Pasteur'), ('GROUP_LEADER', 'Responsable de groupe'), ('ADMIN', 'Administrateur'), ('WEBMASTER', 'Webmaster')], default='MEMBER', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_92a910_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['role'], name='members_mem_role_241778_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='members_mem_is_acti_65d5c9_idx'),
        ),
    ]
